name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
      - run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: prod-app
          baseHref: /
          webRenderer: canvaskit
          customArgs: --dart-define="commit=${{ steps.vars.outputs.sha_short }}"
          